### ISSUE TITLE
Can't add product 5 because it doesn't have a price.

### ISSUE THREAD

**Issue by Yukiri2887** [OrchardCMS/OrchardCore.Commerce#108] opened 2022-04-11 03:29 UTC
Can't add product 5 because it doesn't have a price.
"Your shopping cart is empty."

When i add to chart ,it will show this error.Why?

And how i can use [Orchard Core Commerce Session Cart Storage] and use it on the workflow?
Can this workflow engine use webapi to gone?

**Comment by bleroy** [comment] 2022-04-11 05:16
Duplicate of #105

**Closed by bleroy** 2022-04-11 05:16 UTC

**Comment by bleroy** [comment] 2022-04-11 05:17
You should ask your questions in discussions. Not sure what you mean by "use sessions cart storage and use it on the workflow". Also no idea what "use webapi to gone" means, sorry.
