### ISSUE TITLE
Error adding item to cart if no storage is enabled

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#78] opened 2021-04-23 15:14 UTC
Repro steps: 
- Create an instance with the Agency setup recipe.
- Create a Product Content type using the Product recipe.
- Create a sample product content item.

When you click on `Add to Cart`, an exception occurs:
`Unable to resolve service for type 'OrchardCore.Commerce.Abstractions.IShoppingCartPersistence' while attempting to activate 'OrchardCore.Commerce.Controllers.ShoppingCartController'` because the Session Cart storage module is not enabled.

**Comment by bleroy** [comment] 2021-04-23 18:10
So what do you suggest? Should the product recipe enable the session cart? Seems arbitrary.

The exception looks pretty legit to me in fact. You need to enable a shopping cart to be able to add to a shopping cart.

Another option could be to not add the cart part to the product, but that makes it more confusing, arguably.

Maybe the real issue here is that recipes should cover a whole scenario instead of a narrow one that is useless on its own. I mean, if you just want to create a product type, you don't really need a recipe for that.

So in the end, remove the product recipe and have a "baseline commerce" one?

**Comment by bleroy** [comment] 2021-04-23 18:11
Also, duplicate of #73

**Closed by bleroy** 2021-04-23 18:11 UTC
