### ISSUE TITLE
Prevent checking out if there are unavailable products in the cart (OCC-199)

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore.Commerce#375] opened 2023-11-09 12:02 UTC
### Describe the bug

Currently you can try to check out an order with "Inventory: 0" and it will only fail after the payment is already made.

### To Reproduce

1. Edit a product by setting its Inventory to 0.
2. Try to check it out.
3. See `InvalidOperationException` _after_ the payment has been processed!

### Expected behavior

- The checkout button on the "Your Cart" screen should be greyed out when there is such a product in the cart.
- An error notification of the inventory shortage should be displayed on the cart screen.
- The checkout screen should redirect you back to the cart so this problem can't be bypassed by manually navigating to the `~/checkout` url.

### Screenshots

![gif](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/80963259/420134af-18a5-4a31-affa-aa4207c03a4a)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-199)

**Comment by porgabi** [comment] 2023-11-09 16:57
As far as I can see, the one way to reproduce this is to alter the product's inventory after it's been added to the cart because the "Add to cart" button's clickability is based on the product's inventory (i.e. if it cannot be bought, the button cannot be clicked and the product cannot appear in the cart). I'm fixing that; just wondering if you found other ways to repro the bug?

**Comment by porgabi** [comment] 2023-11-10 16:47
I added the part of the checkout prevention that's responsible for preventing manually navigating to the checkout page and for the redirection back to the cart in `PaymentService`, which requires `PriceVariantsPart` and `IProductService`. This was before I merged the solution changes from #373, after which it no longer works as these are not available in the `Payment` project and cannot be added due to circular dependency.
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/e1f381a7-b0ab-4282-9331-f87b03cb8b65)

This was then used in `PaymentController`'s `Index()` method to determine if checkout is possible.
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/53c6716e-55e9-4034-858c-316606708d49)


373 is a bit of a monster PR to comprehend in one sitting, do you have any suggestions where I could place this logic instead, @sarahelsaig? Or perhaps moving `PriceVariantsPart` and `IProductService` to the `Commerce.Abstractions` project could work?

**Comment by sarahelsaig** [comment] 2023-11-10 19:21
At the start of `IPaymentService.CreateCheckoutViewModelAsync()` we call `ICheckoutEvents.OrderCreatingAsync()`. Similarly, you could add another method to `ICheckoutEvents` which would be called near the end of `IPaymentService.CreateCheckoutViewModelAsync()`. Such as `ICheckoutEvents.ViewModelCreatedAsync()`. Then you can create an appropriate event handler in _OrchardCore.Commerce_ and move your processing logic into it.

**Comment by porgabi** [comment] 2023-11-11 14:47
That does the trick, thanks!

**Closed** 2023-11-20 12:08 UTC
Labels: bug
